name: Jomez Productions
favicon: null
layout_spectrum: 0.726764474529773
typography_spectrum: 0.20072172256186604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8516026840079576
  lightness: 0.21516588260419667
  saturation: 0.932592079276219
  rhythmicContrast: 0.21621473017148674
purpose: []
