name: Jomez Productions
favicon: null
layout_spectrum: 0.49437
typography_spectrum: 0.86899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f3035'
    - '#006d50'
    - '#40b9aa'
    - '#fff8ff'
    - '#888a97'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
